# Generated by Django 4.2 on 2023-11-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="текст сообщения", verbose_name="текст"
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="электронный адрес",
                        max_length=254,
                        verbose_name="e-mail",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="время создания",
                        verbose_name="создано",
                    ),
                ),
            ],
            options={
                "verbose_name": "форма обратной связи",
                "verbose_name_plural": "формы обратной связи",
            },
        ),
    ]
