# Generated by Django 4.2 on 2023-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmodel",
            name="name",
            field=models.TextField(
                default="ANONYMOUS",
                help_text="имя указанное как автор при отправлении",
                verbose_name="имя отправителя",
            ),
        ),
    ]
