# Generated by Django 4.2 on 2023-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_feedbackmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("GT", "получено"),
                    ("PR", "в обработке"),
                    ("OK", "ответ дан"),
                ],
                default="GT",
                help_text="статус обработки формы",
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
