# Generated by Django 4.2 on 2023-11-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0005_statuslog_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                help_text="фидбек",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                related_query_name="feedback",
                to="feedback.feedbackmodel",
            ),
        ),
    ]
