# Generated by Django 4.2 on 2023-11-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0008_alter_feedback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="имя указанное как автор при отправлении",
                null=True,
                verbose_name="имя отправителя",
            ),
        ),
    ]
