# Generated by Django 4.2 on 2023-10-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="-",
                max_length=300,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="-",
                max_length=300,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
