# Generated by Django 4.2 on 2023-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_mainimage_alter_gallery_item_delete_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "verbose_name": "дополнительное изображение",
                "verbose_name_plural": "галерея",
            },
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to="catalog/%Y/%m/%d/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                upload_to="catalog/%Y/%m/%d/", verbose_name="изображение"
            ),
        ),
    ]
