# Generated by Django 4.2 on 2023-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Отображать ли товар на главной странице?",
                verbose_name="на главной странице",
            ),
        ),
    ]
