# Generated by Django 4.2 on 2023-10-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0009_alter_category_normalized_name_alter_gallery_item_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="image",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Категория товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                related_query_name="category",
                to="catalog.category",
            ),
        ),
    ]
