# Generated by Django 4.2 on 2023-10-30 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0002_alter_category_normalized_name_and_more_squashed_0010_alter_gallery_item_alter_item_category",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name", "id"),
                "verbose_name": "тег",
                "verbose_name_plural": "тег",
            },
        ),
    ]
