# Generated by Django 4.2 on 2023-10-30 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name", "id"),
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
